# Site settings
title: "Бытовой гид"
description: "Минималистичная база знаний по бытовым вопросам"
lang: ru
timezone: Europe/Moscow
baseurl: ""
url: "https://zubritskii-i.github.io"
markdown: kramdown
theme: null
permalink: pretty
collections:
  category:
    output: true
    permalink: /:name/
plugins:
  - jekyll-sitemap
  - jekyll-feed
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed
  sass_dir: assets/css

nav_data: primary

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
